const services=[
['Litige civil','Civil litigation','Un contrat non respecté, un préjudice ou un conflit entre particuliers? Clarifions vos recours et la voie à suivre.','A broken agreement, harm suffered or a personal dispute? Let’s clarify your options and the way forward.','<path d="M4 8h24M16 4v23M9 28h14M7 8l-5 11h10L7 8ZM25 8l-5 11h10L25 8Z"/>'],
['Litige commercial','Commercial litigation','Préservez les intérêts de votre entreprise face à un différend contractuel, une créance ou un désaccord entre partenaires.','Protect your business interests in contractual disputes, unpaid accounts or disagreements between partners.','<rect x="4" y="10" width="24" height="18" rx="2"/><path d="M11 10V5h10v5M4 17h24M14 16v4h4v-4"/>'],
['Litige familial','Family litigation','Séparation, responsabilités parentales, soutien financier : avançons avec attention dans les décisions qui touchent votre famille.','Separation, parenting responsibilities and financial support: navigate decisions affecting your family with care.','<circle cx="10" cy="9" r="4"/><circle cx="24" cy="10" r="3"/><path d="M2 28v-5a8 8 0 0 1 16 0v5M21 18a7 7 0 0 1 9 7v3"/>'],
['Litige immobilier','Real estate litigation','Un vice caché, un conflit de voisinage ou une transaction contestée? Protégeons vos intérêts immobiliers.','A hidden defect, a neighbourhood conflict or a disputed transaction? Protect your property interests.','<path d="m3 14 13-11 13 11M7 12v17h18V12M13 29V19h6v10"/>'],
['Litige successoral','Estate litigation','Lorsqu’une succession crée des tensions, abordons les désaccords avec rigueur et sensibilité.','When an estate gives rise to tensions, address disagreements with diligence and sensitivity.','<path d="M8 3h12l6 6v20H8ZM20 3v7h6M12 16h10M12 21h10M12 26h6"/>'],
['Litige pénal','Penal litigation','Face à une infraction reprochée, comprenez les enjeux, vos droits et les options de défense adaptées à votre situation.','When facing an alleged offence, understand what is at stake, your rights and the defence options relevant to you.','<path d="m16 3 11 4v9c0 7-11 13-11 13S5 23 5 16V7ZM11 16l4 4 7-8"/>'],
['Droit du logement','Housing law','Locataire ou propriétaire, trouvez des repères clairs face à un désaccord sur le bail ou l’occupation d’un logement.','Tenant or landlord, find clear guidance in a dispute over a lease or the occupancy of a home.','<circle cx="11" cy="12" r="7"/><path d="m16 17 13 13M22 23l4-4M26 27l4-4"/>']];
// French is the primary language on every page load; English is available via the switch.
let language='fr';
function render(){document.documentElement.lang=language;document.querySelectorAll('[data-fr]').forEach(e=>e.innerHTML=e.dataset[language]);document.querySelector('.language').textContent=language==='fr'?'EN':'FR';document.querySelector('.language').setAttribute('aria-label',language==='fr'?'Switch to English':'Passer en français');document.querySelector('nav').setAttribute('aria-label',language==='fr'?'Navigation principale':'Main navigation');document.querySelector('#service-grid').innerHTML=services.map(s=>`<a class="service" href="#contact"><svg viewBox="0 0 32 32" aria-hidden="true">${s[4]}</svg><span class="arrow" aria-hidden="true"><svg class="icon-arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></span><h3>${s[language==='fr'?0:1]}</h3><p>${s[language==='fr'?2:3]}</p></a>`).join('')+`<a class="service cta" href="#contact"><h3>${language==='fr'?'Votre situation<br>est unique.':'Your situation<br>is unique.'}</h3><p>${language==='fr'?'Prenons le temps d’en parler.':'Let’s take the time to discuss it.'}</p><span class="arrow" aria-hidden="true"><svg class="icon-arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></span></a>`;document.querySelector('meta[name="description"]').content=language==='fr'?'Une écoute attentive. Des conseils clairs. Une défense déterminée. Découvrez les services juridiques de Maxime Vincent.':'Attentive listening. Clear advice. Determined advocacy. Explore Maxime Vincent’s legal services.';}
document.querySelector('.language').addEventListener('click',()=>{language=language==='fr'?'en':'fr';render()});render();
